apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch                         # <-- keeps the old service DNS name
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "0"      # sync after the operator
spec:
  general:
    version: latest                        # bump at will; operator rolls forward :contentReference[oaicite:1]{index=1}
    serviceName: opensearch-service                # generates headless & ClusterIP svc
    httpPort: 9200
    drainDataNodes: true
    env:
      - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            name: opensearch-initial-admin-password
            key: OPENSEARCH_INITIAL_ADMIN_PASSWORD
  dashboards:
    enable: true
    replicas: 1
    version: latest
  nodePools:
    - component: cluster-manager
      replicas: 3
      roles: ["cluster_manager"]
      diskSize: 10Gi
    - component: data
      replicas: 2
      roles: ["data","ingest","remote_cluster_client"]
      diskSize: 20Gi
  security:
    config:
      # reuse the secret you already create in README
      adminCredentialsSecret:
        name: admin-credentials-secret
      securityConfigSecret:
        name: securityconfig-secret
