apiVersion: opensearch.opensearch.org/v1
kind: OpenSearchCluster
metadata:
  name: opensearch          # <— keeps the old service names alive
  namespace: default
spec:
  general:
    serviceName: opensearch
    version: "2.7.0"
  dashboards:               # UI, replaces the old deployment
    enable: true            # operator makes a Service called opensearch-dashboards
    replicas: 1
  nodePools:
    - component: cluster-manager
      replicas: 1
      roles: ["cluster_manager","data","ingest"]
      persistence:
        size: 10Gi
    - component: data
      replicas: 1
      roles: ["data","ingest"]
      persistence:
        size: 10Gi
