apiVersion: v1
kind: Service
metadata:
  name: opensearch-service
  labels:
    app: opensearch
spec:
  clusterIP: None
  selector:
    app: opensearch
  ports:
    - name: rest
      port: 9200
    - name: performance
      port: 9600
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch-dashboard
spec:
  selector:
    app: opensearch-dashboard
  ports:
    - name: http
      port: 5601
      targetPort: 5601
  type: NodePort
