apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: document-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/document-manager-idp/k8s-infrastructure.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true