apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: document-manager-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      location ~* "^/dashboard" {
        rewrite ^(/dashboard.*) $1 break;
      }
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /auth/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-service
                port:
                  number: 3000
          - path: /api/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: business-logic-service
                port:
                  number: 5000
          - path: /dashboard/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: opensearch-service-dashboards
                port:
                  number: 5601
