grafana:
  ingress:
    enabled: true
  service:
      type: ClusterIP
      port: 3000           # match your ingress backend port
      targetPort: 3000     # Grafana container listens on 3000
  rootUrl: "%(protocol)s://%(domain)s/grafana"
  serveFromSubPath: true
  adminUser: admin
  adminPassword: admin

prometheus:
  prometheusSpec:
    serviceMonitorSelector:
      matchLabels:
        app: document-manager
