grafana:
  ingress:
    enabled: true
  service:
      type: ClusterIP
      port: 3000           # match your ingress backend port
      targetPort: 3000     # Grafana container listens on 3000
  adminUser: admin
  adminPassword: admin

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'dashboards'
          orgId: 1
          folder: 'Kubernetes'
          type: file
          disableDeletion: true
          editable: true
          options:
            path:  /var/lib/grafana/dashboards
  dashboards:
    default:
      auth-service:
        file: dashboards/auth-service.json
      business-service:
        file: dashboards/business-service.json

  grafana.ini:
    server:
      domain: localhost
      root_url: "%(protocol)s://%(domain)/grafana/"
      serve_from_sub_path: true

prometheus:
  prometheusSpec:
    serviceMonitorSelector:
      matchLabels:
        app: document-manager
