apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: ghcr.io/document-manager-idp/auth-service:01753dd5582e3e600278243d9eaba59cd640e0ff
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: HOSTNAME
              value: localhost
            - name: PORT
              value: "3000"
            - name: REDIRECT_URL
              value: http://localhost
            - name: COGNITO_SECRET
              valueFrom:
                secretKeyRef:
                  name: cognito-secret
                  key: COGNITO_SECRET
