apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: ghcr.io/document-manager-idp/auth-service:b9ac1e965b081bc9b788bd7046335d9d3d245592
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: HOSTNAME
              value: localhost
            - name: PORT
              value: "3000"
            - name: REDIRECT_URL
              value: http://localhost
            - name: COGNITO_SECRET
              valueFrom:
                secretKeyRef:
                  name: cognito-secret
                  key: COGNITO_SECRET
