apiVersion: v1
kind: Service
metadata:
  name: business-logic-service
spec:
  selector:
    app: business-logic-service
  ports:
    - port: 5000
      targetPort: 5000
      name: http
  type: ClusterIP
