apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: database-service
  template:
    metadata:
      labels:
        app: database-service
    spec:
      containers:
        - name: database-service
          image: ghcr.io/document-manager-idp/db-service:71a0e344aacb2dcf45b263d94c0cc3bfb37de05a
          ports:
            - containerPort: 5700
          env:
            - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: opensearch-initial-admin-password
                  key: OPENSEARCH_INITIAL_ADMIN_PASSWORD
            - name: OPENSEARCH_ADDRESS
              value: localhost
