apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-service
  template:
    metadata:
      labels:
        app: database-service
    spec:
      containers:
        - name: database-service
          image: ghcr.io/document-manager-idp/db-service:21fedf3f4f6fdbaf7a9248fa389c0a7f47e8d04b
          ports:
            - containerPort: 5700
          env:
            - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: opensearch-initial-admin-password
                  key: OPENSEARCH_INITIAL_ADMIN_PASSWORD
            - name: OPENSEARCH_ADDRESS
              value: opensearch-service.default.svc
