apiVersion: v1
kind: Service
metadata:
  name: database-service
  labels:
    app: database-service
spec:
  selector:
    app: database-service
  ports:
    - port: 5700
      targetPort: 5700
      name: http
  type: ClusterIP
